---
- name: Install EPEL Repo package from standard repo
  dnf:
   name: epel-release
   state: present
- name: Add Elastic repo GPG key.
  rpm_key:
    key: "{{ repo_key }}"
    state: present
- name: Adding Elasticsearch Repo
  yum_repository:
    baseurl: "{{ repo_url }}"
    description: "Elasticsearch repository"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ repo_key }}"
    name: "Elastic repo"
    state: present
- name: Install Elasticsearch package
  dnf:
   name: elasticsearch
   state: latest
  tags:
   - packages  
- name: Create Elasticsearch config file from template
  template:
   src: elasticsearch.yml.j2
   dest: /etc/elasticsearch/elasticsearch.yml
   nowner: root
   group: elasticsearch
   mode: "0660"
  notify:
   - Restart elasticsearch
- name: Create firewalld rule for NGINX
  firewalld:
    port: "{{ nginx_listen_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled