# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_RAM = 1024
BOX_CPU = 2

Vagrant.configure(2) do |config|
  config.vm.box = "kgeor/rocky9-kernel6"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = BOX_RAM
      vb.cpus = BOX_CPU
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
  end
  config.vm.define "log-server" do |server|
    server.vm.hostname = "rocky9-log"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end
    server.vm.network "private_network", virtualbox__intnet: "LAN", auto_config: false
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbook.yml"
      ansible.host_vars = {
        "log-server" => { "ip_addr" => "10.0.5.10/24"}
      }
      ansible.compatibility_mode = "2.0"
    end
  end
  config.vm.define "nginx" do |client|
    client.vm.hostname = "rocky9-web"
    client.vm.network "private_network", virtualbox__intnet: "LAN", auto_config: false
    client.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbook.yml"
      ansible.host_vars = {
        "nginx" => { "ip_addr" => "10.0.5.11/24"}
      }
      ansible.compatibility_mode = "2.0"
    end
  end 
end