# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_RAM = 1024
BOX_CPU = 2

Vagrant.configure(2) do |config|
  config.vm.box = "kgeor/rocky9-kernel6"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = BOX_RAM
      vb.cpus = BOX_CPU
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
  end
  
  config.vm.define "docker" do |server|
    server.vm.hostname = "docker-host"
    server.vm.network "forwarded_port", guest: 8083, host: 8083
    server.vm.network "forwarded_port", guest: 8081, host: 8081
    server.vm.network "forwarded_port", guest: 8082, host: 8082

    server.vm.network "private_network", auto_config: false, virtualbox__intnet: true
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbook.yml"
      #ansible.raw_arguments = ["--tags=docker"]
      #ansible.host_vars = {
      #  "docker" => { "ip_addr" => "192.168.50.10/24",
      #  }
      #}
      ansible.compatibility_mode = "2.0"
    end
  end 
end