# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_RAM = 1024
BOX_CPU = 2

Vagrant.configure(2) do |config|
  config.vm.box = "kgeor/rocky9-kernel6"
  config.vm.synced_folder ".", "/vagrant", automount: true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = BOX_RAM
    vb.cpus = BOX_CPU
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
  end
  config.vm.define "borg-server" do |server|
    server.vm.hostname = "rocky9-borg-server"
    server.vm.provider "virtualbox" do |vb|
      unless File.exist?("disk-1.vdi")
        vb.customize [ "createmedium", "disk", "--filename", "disk-1.vdi", "--format", "vdi", "--size", "2048"]
      end
      vb.customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", "1", "--device", 0, "--type", "hdd", "--medium", "disk-1.vdi"]
    end
    server.vm.network "private_network",
      auto_config: false,
      virtualbox__intnet: "p2p",
      nic_type: "82545EM"
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbook.yml"
      ansible.host_vars = {
        "borg-server" => { "ip_addr" => "10.0.5.10/24"}
      }
      ansible.raw_arguments = ["--tags=general,server"]
      ansible.compatibility_mode = "2.0"
    end
  end
  config.vm.define "borg-client" do |client|
    client.vm.hostname = "rocky9-borg-client"
    client.vm.network "private_network", 
      auto_config: false,
      virtualbox__intnet: "p2p",
      nic_type: "82545EM"
    client.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbook.yml"
      ansible.host_vars = {
        "borg-client" => {"ip_addr" => "10.0.5.11/24"}
      }
      ansible.raw_arguments = ["--tags=general,client"]
      ansible.compatibility_mode = "2.0"
    end
  end 
end