# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_RAM = 512
BOX_CPU = 1
MACHINES = {
  :inetRouter => {
    :box_name => "kgeor/rocky9-kernel6",
    :vm_name => "inetRouter",
    :net => [
      {adapter: 2, autoconfig: false, virtualbox__intnet: "router-net"},
      {ip: '192.168.56.10', adapter: 8},
    ]
  },

  :centralRouter => {
    :box_name => "kgeor/rocky9-kernel6",
    :vm_name => "centralRouter",
    # ip addresses below specifying only for ref.
    :net => [
      {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", auto_config: false, virtualbox__intnet: "router-net"},
      {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", auto_config: false, virtualbox__intnet: "dir-net"},
      {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", auto_config: false, virtualbox__intnet: "hw-net"},
      {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", auto_config: false, virtualbox__intnet: "mgt-net"},
      {ip: '192.168.255.9', adapter: 6, netmask: "255.255.255.252", auto_config: false, virtualbox__intnet: "office1-central"},
      {ip: '192.168.255.5', adapter: 7, netmask: "255.255.255.252", auto_config: false, virtualbox__intnet: "office2-central"},
      {ip: '192.168.56.11', adapter: 8},
    ]
  },

  :centralServer => {
    :box_name => "kgeor/rocky9-kernel6",
    :vm_name => "centralServer",
    :net => [
      {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", auto_config: false, virtualbox__intnet: "dir-net"},
      {ip: '192.168.56.12', adapter: 8},
    ]          
  },

  :office1Router => {
    :box_name => "ubuntu/jammy64",
    :vm_name => "office1Router",
    :net => [
      {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
      {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev1-net"},
      {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
      {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "managers-net"},
      {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "office1-net"},
      {ip: '192.168.56.20', adapter: 8},
    ]
  },

  :office1Server => {
    :box_name => "ubuntu/jammy64",
    :vm_name => "office1Server",
    :net => [
      {ip: '192.168.2.130', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "managers-net"},
      {ip: '192.168.56.21', adapter: 8},
    ]
  },

  :office2Router => {
    :box_name => "debian/bookworm64",
    :vm_name => "office2Router",
    :net => [
               {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office2-central"},
               {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
               {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test2-net"},
               {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office2-net"},
               {ip: '192.168.56.30', adapter: 8},
            ]
  },

  :office2Server => {
    :box_name => "debian/bookworm64",
    :vm_name => "office2Server",
    :net => [
               {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
               {ip: '192.168.56.31', adapter: 8},
            ]
}
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false  
    end
    config.vm.provider "virtualbox" do |vb|
      vb.memory = BOX_RAM
      vb.cpus = BOX_CPU
    end
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", **ipconf
      end
      box.vm.provision "ansible" do |ansible|
        ansible.playbook = "./ansible/playbook.yml"
        ansible.host_vars = {
          "inetRouter" => { 
                            "ip_addr" => "192.168.255.1/30",
                            "ip_nh_cr" => "192.168.255.2"
                          },
          "centralRouter" => { "ip_addr_1" => "192.168.255.2/30",
                               "ip_addr_2" => "192.168.0.1/28",
                               "ip_addr_3" => "192.168.0.33/28",
                               "ip_addr_4" => "192.168.0.65/26",
                               "ip_addr_5" => "192.168.255.9/30",
                               "ip_addr_6" => "192.168.255.5/30",
                               "ip_gw" => "192.168.255.1",
                               "ip_nh_o1" => "192.168.255.10",
                               "ip_nh_o2" => "192.168.255.6",
                             },
          "centralServer" => { 
                               "ip_addr_1" => "192.168.0.2/28",
                               "ip_gw" => "192.168.0.1",
                             }
        }
        ansible.compatibility_mode = "2.0"
        ansible.limit = boxconfig[:vm_name]
      end
    end
  end
end
