# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_RAM = 2048
BOX_CPU = 2

Vagrant.configure(2) do |config|
  config.vm.box = "kgeor/rocky9-kernel6"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = BOX_RAM
    vb.cpus = BOX_CPU
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
  end
  config.vm.define "pxe-server" do |server|
    server.vm.hostname = "pxe-server"
    server.vm.network "private_network", virtualbox__intnet: "pxenet", auto_config: false
    #server.vm.network "forwarded_port", guest: 80, host: 80
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbook.yml"
      ansible.limit = "pxe-server"
      ansible.compatibility_mode = "2.0"
    end
  end
  config.vm.define "pxe-client" do |client|
    client.vm.hostname = "pxe-client"
    client.vm.provider "virtualbox" do |vb|
      #unless File.exist?("disk-1.vdi")
      #  vb.customize [ "createmedium", "disk", "--filename", "disk-1.vdi", "--format", "vdi", "--size", "8192"]
      #end
      #vb.customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", "0", "--device", 0, "--type", "hdd", "--medium", "disk-1.vdi"]
      vb.customize ["modifyvm", :id,
        #"--firmware", "efi",
        "--boot1", "net",
        "--boot2", "none",
        "--boot3", "none",
        "--boot4", "none",
        "--nicbootprio2", "1"
      ]
    end
    client.vm.network "private_network", virtualbox__intnet: "pxenet", auto_config: false
  end 
end