# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  # Указываем ОС, версию, количество ядер и ОЗУ
  config.vm.box = "kgeor/rocky9-kernel6"
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 1
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
  end
  # Указываем имена хостов и их IP-адреса
  boxes = [
    { :name => "ipa.otus.lan",
      :ip => "192.168.57.10",
    },
    { :name => "client1.otus.lan",
      :ip => "192.168.57.11",
    },
    { :name => "client2.otus.lan",
      :ip => "192.168.57.12",
    }
  ]
  # Цикл запуска виртуальных машин
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", auto_config: false, virtualbox__intnet: "domain"
      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.host_vars = {
          "ipa.otus.lan"      => { 
                                    "ip" => "192.168.57.10/24"
                                 },
          "client1.otus.lan"  => {
                                    "ip" => "192.168.57.11/24"
                                 },
          "client2.otus.lan"  => {
                                    "ip" => "192.168.57.12/24"
                                 }
        }
        ansible.compatibility_mode = "2.0"
      end
    end
  end
end
