{
 "title": "HAproxy",
 "tags": [ "haproxy" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "time_interval", "query": "5m, 10m, 30m, 1h, 4h, 8h" }
  ]
 },
 "panels": [
  {
   "title": "Frontend",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_frontend_status{proxy=\"db_front\", state=\"UP\"}",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Current sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_process_uptime_seconds/3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend servers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_status{state=\"UP\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Backend response error/deny",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "haproxy_backend_responses_denied_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "haproxy_backend_response_errors_total",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Frontend requests error/deny",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "haproxy_frontend_request_errors_total{proxy=\"db_front\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "haproxy_frontend_requests_denied_total{proxy=\"db_front\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}