# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
        :box_name => "kgeor/rocky9-kernel6",

        :vm_name => "inetRouter",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                   {ip: '192.168.56.10', adapter: 8},
                ]
  },

  :centralRouter => {
        :box_name => "kgeor/rocky9-kernel6",

        :vm_name => "centralRouter",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                   #{ip: '192.168.255.9', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
                   {ip: '192.168.56.11', adapter: 8},
                ]
  },

  :office1Router => {
        :box_name => "kgeor/rocky9-kernel6",

        :vm_name => "office1Router",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "office1-central"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: "vlan1"},
                   {adapter: 4, auto_config: false, virtualbox__intnet: "vlan1"},
                   {adapter: 5, auto_config: false, virtualbox__intnet: "vlan2"},
                   {adapter: 6, auto_config: false, virtualbox__intnet: "vlan2"},
                   {ip: '192.168.56.20', adapter: 8},
                ]
  },

  :testClient1 => {
        :box_name => "kgeor/rocky9-kernel6",

        :vm_name => "testClient1",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
                   {ip: '192.168.56.21', adapter: 8},
                ]
  },

  :testServer1 => {
        :box_name => "kgeor/rocky9-kernel6",

        :vm_name => "testServer1",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
                   {ip: '192.168.56.22', adapter: 8},
            ]
  },

  :testClient2 => {
        :box_name => "ubuntu/jammy64",
        #:box_version => "20220411.2.0",
        :vm_name => "testClient2",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
                   {ip: '192.168.56.31', adapter: 8},
                ]
  },

  :testServer2 => {
        :box_name => "ubuntu/jammy64",
        #:box_version => "20220411.2.0",
        :vm_name => "testServer2",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
                   {ip: '192.168.56.32', adapter: 8},
                ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    
    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      #box.vm.box_version = boxconfig[:box_version]
      if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.auto_update = false  
      end
      config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 2
       end

      box.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        #ansible.inventory_path = "ansible/hosts"
        #ansible.host_key_checking = "false"
        #ansible.become = "true"
        ansible.host_vars = {
          "inetRouter"    => { 
                               "ip" => "192.168.255.1/30"
                             },
          "centralRouter" => {
                               "ip" => "192.168.255.2/30"
                             },  
          "testClient1" => { 
                             "vlan_id" => "1",
                             "ip" => "10.10.10.254/24"
                           },    
          "testServer1" => { 
                             "vlan_id" => "1",
                             "ip" => "10.10.10.1/24"
                           },
          "testClient2" => { 
                            "vlan_id" => "2",
                            "ip" => "10.10.10.254/24"
                           },
          "testServer2" => {
                             "vlan_id" => "2",
                             "ip" => "10.10.10.1/24"
                           }  
        }
        ansible.limit = boxconfig[:vm_name]
        ansible.compatibility_mode = "2.0"
      end

      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", **ipconf
      end
    end
  end
end
