---
- hosts: all
  become: true
  tasks:
  -  name: Setting up common config
     block:
     - name: Installing EPEL Repo package from standard repo
       ansible.builtin.dnf:
         name: epel-release
         state: present

     - name: Deleting default Ethernet connection with DHCP
       community.general.nmcli:
         conn_name: "Wired connection 1"
         state: absent
         
     - name: Adding an Ethernet connection with static IP configuration
       community.general.nmcli:
         conn_name: enp0s8
         ifname: enp0s8
         type: ethernet
         ip4: "{{ ip_addr }}"
         state: present
  roles:
    - role: borg