---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: true
      dhcp4-overrides:
        use-routes: false
    enp0s8:
      addresses:
      - 192.168.2.130/26
      routes:
        - to: default
          via: 192.168.2.129
    enp0s19:
      addresses:
      - 192.168.56.21/24
