---
- hosts: nginx
  become: true
  roles:
    - nginx
- hosts: log-server
  become: true
  roles:
    - rsyslog
#- hosts: elk
#  become: true
#  roles:
#    - elastic
#    - logstash
#    - kibana