---
- hosts: all
  become: true
  tasks:
    - name: Deleting default Ethernet connection with DHCP
      community.general.nmcli:
        conn_name: "Wired connection 1"
        state: absent
    
    - name: Adding an Ethernet connection with static IP configuration
      community.general.nmcli:
        conn_name: enp0s8
        ifname: enp0s8
        type: ethernet
        ip4: "{{ ip_addr }}"
        state: present

- hosts: nginx
  become: true
  roles:
    - nginx

- hosts: log-server
  become: true
  roles:
    - rsyslog
#- hosts: elk
#  become: true
#  roles:
#    - elastic
#    - logstash
#    - kibana