# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_RAM = 1024
BOX_CPU = 2

Vagrant.configure(2) do |config|
  config.vm.box = "kgeor/rocky9-kernel6"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = BOX_RAM
      vb.cpus = BOX_CPU
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
  end
  config.vm.define "server" do |server|
    server.vm.hostname = "server.loc"
    server.vm.network "private_network", ip: "192.168.56.10", auto_config: false
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbook.yml"
      ansible.limit = "server"
      ansible.host_vars = {
        "server" => { "ip_addr" => "192.168.56.10/24"}
      }
      ansible.compatibility_mode = "2.0"
    end
  end
  config.vm.define "client" do |client|
    client.vm.hostname = "client.loc"
    client.vm.network "private_network", ip: "192.168.56.20", auto_config: false
    client.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbook.yml"
      ansible.limit = "client"
      ansible.host_vars = {
        "client" => { "ip_addr" => "192.168.56.20/24"}
      }
      ansible.compatibility_mode = "2.0"
    end
  end 
end