apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090 
  isDefault: true
  access: proxy
  editable: true

- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  #basicAuth: false
  #isDefault: true
  #version: 1
  editable: true

- name: Alertmanager
  type: alertmanager
  implementation: Prometheus
  url: http://alertmanager:9093
  access: proxy
  editable: true
  jsonData:
    implementation: prometheus