# -*- mode: ruby -*-
# vi: set ft=ruby :
MACHINES = {
  :node1 => {
        # VM box
        :box_name => "kgeor/rocky9-kernel6",
        # Имя VM
        :vm_name => "node1",
        # Количество ядер CPU
        :cpus => 2,
        # Указываем количество ОЗУ (В Мегабайтах)
        :memory => 1024,
        # Указываем IP-адрес для ВМ
        :ip => "192.168.57.11",
  },
  :node2 => {
        :box_name => "kgeor/rocky9-kernel6",
        :vm_name => "node2",
        :cpus => 2,
        :memory => 1024,
        :ip => "192.168.57.12",

  },
  :barman => {
        :box_name => "kgeor/rocky9-kernel6",
        :vm_name => "barman",
        :cpus => 1,
        :memory => 1024,
        :ip => "192.168.57.13",
  },
}

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
  end
  
  MACHINES.each do |boxname, boxconfig|
    
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      box.vm.network "private_network", ip: boxconfig[:ip], auto_config: false, virtualbox__intnet: "lan"
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end

      box.vm.provision "ansible" do |ansible|
        ansible.playbook = "./ansible/playbook.yml"
        ansible.limit = boxconfig[:vm_name]
        ansible.host_vars = {
          "node1" => { "ip_addr" => "192.168.57.11/24"},
          "node2" => { "ip_addr" => "192.168.57.12/24"},
          "barman" => { "ip_addr" => "192.168.57.13/24"}
        }
        ansible.raw_arguments = ["--tags=untagged"]
        ansible.compatibility_mode = "2.0"
      end
    end
  end
end