global:
  scrape_interval: 5s
  scrape_timeout: 5s
  # evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'haproxy'
    metrics_path: '/prom'
    static_configs:
      - targets: ['haproxy:8405']
      
  - job_name: 'mysql' # To get metrics about the mysql exporter’s targets
    params:
      # Not required. Will match value to child in config file. Default value is `client`.
      auth_module: [client]
    static_configs:
      - targets:
        # All mysql hostnames or unix sockets to monitor.
        - db1:3306
        - db2:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # The mysqld_exporter host:port
        replacement: mysql-exporter:9104
  
  - job_name: 'nginx'
    metrics_path: '/prom'
    static_configs:
      - targets: ['nginx-exporter:9113']

rule_files:
 - rules.yml

alerting:
 alertmanagers:
 - static_configs:
   - targets:
      - alertmanager:9093

#remote_write:
#  - url: '<Your Prometheus remote_write endpoint>'
#    basic_auth:
#      username: '<Your Grafana Username>'
#      password: '<Your Grafana API key>'