source_directories: []
repositories:
    - path: /opt/backup/borg-repository/
      label: local-db
#one_file_system: true

#storage:
##   Passphrase is set in variable $BORG_PASSPHRASE
##   encryption_passphrase: "DoNotMissToChangeYourPassphrase"
#    compression: lz4
archive_name_format: 'db-{now:%Y-%m-%dT%H:%M:%S}'

keep_hourly: 4
keep_daily: 10
keep_weekly: 4
keep_monthly: 12

checks:
    - name: repository
    - name: archives
      frequency: 2 days

#hooks:
loki:
    url: http://localhost:3100/loki/api/v1/push
    labels:
        job: borgmatic
before_backup:
    - echo "Starting DB backup job."
mysql_databases:
    - name: wordpress
      hostname: 172.16.5.110
      port: 3306
      username: root
      password: dbpassword
      options: "--skip-comments --single-transaction"
after_backup:
    - echo "DB backup created."
on_error:
    - echo "Error while creating DB backup."
