# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_RAM = 512
BOX_CPU = 1

Vagrant.configure(2) do |config|
  config.vm.box = "kgeor/rocky9-kernel6"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = BOX_RAM
      vb.cpus = BOX_CPU
      vb.customize ["modifyvm", :id, "--nic3", "intnet"]
      vb.customize ["modifyvm", :id, "--nictype3", "82545EM"]
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
  end
  config.vm.define "rocky9" do |server|
    server.vm.hostname = "rocky9-pam"
    server.vm.network "private_network", ip: "192.168.56.15"
    server.vm.provision "shell", path: "setup.sh"
  end
end