# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_RAM = 2048
BOX_CPU = 2

Vagrant.configure(2) do |config|
  config.vm.box = "kgeor/lab6"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = BOX_RAM
      vb.cpus = BOX_CPU
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
  end
  config.vm.define "r9-rpm" do |server|
    server.vm.hostname = "r9-rpm"
    #server.vm.provision "shell", path: "setup.sh"
  end
end